version: '3.8'

services:
  graphdb:
    image: ontotext/graphdb:10.6.1
    container_name: graphdb
    ports:
      - "7200:7200"
    volumes:
      - graphdb-data:/opt/graphdb/home
    restart: unless-stopped

  vocbench:
    image: sha256:d5e45552a2aa695ba4357d2ec5df208484c0677f2a820268d002b71f1878d923
    container_name: vocbench
    ports:
      - "1979:1979"
    environment:
      - JAVA_OPTS=-Xmx2g
    restart: unless-stopped

  skosmos:
    #image: natlibfi/skosmos
    image: ndslabs/skosmos
    container_name: skosmos
    ports:
      - "8080:80"
    volumes:
      - ./skosmos/config:/var/www/html/config
    depends_on:
      - graphdb
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    restart: unless-stopped

  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-runner
    environment:
      - REPO_URL=https://github.com/Fl4gell4nt/qa-kg
      - RUNNER_NAME=docker-runner
      - RUNNER_TOKEN=YOUR_GITHUB_RUNNER_TOKEN
      - RUNNER_WORKDIR=/tmp/github-runner
      - LABELS=self-hosted,docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  graphdb-data:
  jenkins-data:
